#
#   Defines
#
BASEDIR		:=	../

INCLUDES	:= \
	-I./ \

CFLAGS		:= \
	-rdynamic \
	-funwind-tables \

LIBS		:= \
	-lpthread \

#
#   Target object
#
TARGET_NAME	:=	coseq

#
#   Target type
#     (EXEC/SHARED/STATIC/OBJECT)
#
TARGET_TYPE	:=	SHARED

#
#   Compile sources
#
SRCS		:= \
	coseq.c \

INSTALL_HEADERS := \
	coseq_if.h \

#
#   Configurations
#
include $(BASEDIR)/Config.mak
